//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASYGEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUITS
    {
        public int idProduit { get; set; }
        public string nomProduit { get; set; }
        public string description { get; set; }
        public Nullable<int> prix_ht { get; set; }
        public Nullable<int> prix_ttc { get; set; }
        public Nullable<int> idCategorie { get; set; }
    }
}
